import{a as q,S as P,i as s}from"./assets/vendor-DvfmeZXB.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const R="53389893-16eb2ee6e433eb21b924fd0ec",E="https://pixabay.com/api/",$=15;async function m(i,t=1){const r={key:R,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:$};return(await q.get(E,{params:r})).data}const y=document.querySelector(".gallery"),n=document.querySelector(".loader"),a=document.querySelector(".btn"),B=new P(".gallery a",{captionsData:"alt",captionDelay:250});function b(i){const t=i.map(({webformatURL:r,largeImageURL:c,tags:e,likes:o,views:l,comments:w,downloads:S})=>`
      <li class="gallery-item">
        <a href="${c}">
          <img src="${r}" alt="${e}" loading="lazy"/>
        </a>
        <div class="info">
          <p><b>Likes</b> ${o}</p>
          <p><b>Views</b> ${l}</p>
          <p><b>Comments</b> ${w}</p>
          <p><b>Downloads</b> ${S}</p>
        </div>
      </li>
    `).join("");y.insertAdjacentHTML("beforeend",t),B.refresh()}function O(){y.innerHTML=""}function L(){n==null||n.classList.add("is-active")}function p(){n==null||n.classList.remove("is-active")}function x(){a==null||a.classList.remove("is-hidden")}function f(){a==null||a.classList.add("is-hidden")}const u={form:document.querySelector(".form"),input:document.querySelector('input[name="search-text"]'),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".btn")};let g=1,v="",d=0,h=0;u.loadMoreBtn.classList.add("is-hidden");u.form.addEventListener("submit",async i=>{i.preventDefault();const t=u.input.value.trim();if(!t){s.warning({title:"Warning",message:"Please enter a search term.",position:"topRight"});return}v=t,u.input.value="",g=1,d=0,h=0,O(),f(),L();try{const r=await m(t,g);if(p(),!r.hits||r.hits.length===0){s.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h=r.totalHits??0,d=r.hits.length,b(r.hits),d<h?x():(f(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{p(),s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}});u.loadMoreBtn.addEventListener("click",async()=>{g+=1,L();try{const i=await m(v,g);if(p(),!i.hits||i.hits.length===0){f(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}b(i.hits),d+=i.hits.length;const t=document.querySelector(".gallery-item");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}if(d>=h){f(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}}catch{p(),s.error({title:"Error",message:"Unable to load more images.",position:"topRight"})}});
//# sourceMappingURL=index.js.map
